#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2024/10/28 20:17:20
# Search URL: http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.CAS.FGOALS-g3.ssp126.r1i1p1f1.day.tas.gn.v20200928|esgf-data1.llnl.gov
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.CAS.FGOALS-g3.ssp126.r1i1p1f1.day.tas.gn.v20200928|esgf-data1.llnl.gov'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20150101-20151231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20150101-20151231.nc' 'SHA256' '6a90e64f5b3593e08d173f127fccbd7221fca37f0d62f90a97f489005f99ae47'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20160101-20161231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20160101-20161231.nc' 'SHA256' '48e850ad49d23ec21d42915c631155879e81bb47549dd0014ef5ef725e73eb77'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20170101-20171231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20170101-20171231.nc' 'SHA256' 'aa33d0032312b1f1d69a0beeaba2c531662225141a05f8d1fa4549c7c121bbba'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20180101-20181231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20180101-20181231.nc' 'SHA256' 'a4843bb30930c1ec0fc93881d95dc04610ff85ccf2a929a85e69d2fc8984c37d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20190101-20191231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20190101-20191231.nc' 'SHA256' 'c5c8e94bafccb92514d995ab843ad6323e3150c982b4524c141e36a79d300c54'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20200101-20201231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20200101-20201231.nc' 'SHA256' 'fd307541224ab6107c9e38ca6620a4610ab01a2e33c2f821427ca41ef1811644'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20210101-20211231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20210101-20211231.nc' 'SHA256' '848caf54200e4e08075ab29e3e205cd5d7414c9933d35d6a857ea6d497f10a73'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20220101-20221231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20220101-20221231.nc' 'SHA256' '7f29e035e70ef261e623f35f13333714475c6d8c60ab8241b6e3641725841538'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20230101-20231231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20230101-20231231.nc' 'SHA256' '378188c7095f920953d6e7049b7f7399039df21fc288f1d0143a5cd13961bc4f'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20240101-20241231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20240101-20241231.nc' 'SHA256' 'c49d5a11ff8f8929487bc315adf6394f56b4377d67366fa1e96a17182d198d75'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20250101-20251231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20250101-20251231.nc' 'SHA256' 'dc61dfa4ded178e9c8c7c03a66329b9cdf11c147f912fb956294131a630a4765'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20260101-20261231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20260101-20261231.nc' 'SHA256' '9c31e4b3a6b50a2f79c61b5972cd5a112b52114aea3ec4eeaf4d30f5ede6cf4a'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20270101-20271231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20270101-20271231.nc' 'SHA256' '96dbc73f513347b0675f752bd7e1741c51e7a814924aee012a2eabf1eae536ec'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20280101-20281231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20280101-20281231.nc' 'SHA256' '38c1b81de545a4d3b32aa790e6881801b2ed8e39707142b31287eff2361881c0'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20290101-20291231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20290101-20291231.nc' 'SHA256' 'f01637aab5a4c6ed6993aefb370021628a4915ae6749f0b1d3c9552060acd51d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20300101-20301231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20300101-20301231.nc' 'SHA256' 'a9395330c319771dfca09b441a37d1fe132a5e37c4f256bcba2ab7d200771fd7'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20310101-20311231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20310101-20311231.nc' 'SHA256' '5227c7b4973af66b10aacd145798c65e6cbf441c930087b1cc69871c6e02b180'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20320101-20321231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20320101-20321231.nc' 'SHA256' 'afe29f2b9f0873708047b97df3f49ac94d369030a0bac5a1ce9be6140e270bc7'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20330101-20331231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20330101-20331231.nc' 'SHA256' '8e1568025a0971a96e3ddc01dafe9f3e8ab076f0c09f04364c8362068ff2a01a'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20340101-20341231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20340101-20341231.nc' 'SHA256' 'a69ffa5dfbd9c15485c2240079d1d2a511fae1a26b4238ccb095ecd69be6ff86'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20350101-20351231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20350101-20351231.nc' 'SHA256' '0062fdfdde80379aa93f339141d4d1b49c9cfda4475a9253c5cfd8825788d626'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20360101-20361231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20360101-20361231.nc' 'SHA256' 'c36c9006bbea88d598e0d433af2dc39ba17606ef3a1f217821d8387bbded4846'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20370101-20371231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20370101-20371231.nc' 'SHA256' '6510ba229e2798c8ba058c03cf2e40280e98bdcaaf800e7c4dd8795545921424'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20380101-20381231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20380101-20381231.nc' 'SHA256' '60337deea6ee5dc104d6087ceeaad2a2eadf9585ebc51ade1cb34ef2f63a1425'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20390101-20391231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20390101-20391231.nc' 'SHA256' 'c31783fb9de3c861a8982729fe49645bfc73fa6c4eee28c3429a8745b7b19ce0'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20400101-20401231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20400101-20401231.nc' 'SHA256' '083ac2ad54c34a96a381e9cced17ce7fd71f4454befd318e3fbf064d2086f8e8'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20410101-20411231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20410101-20411231.nc' 'SHA256' '8e5c80d7e5fc71a76f1126ff27fb4c0c00ed1be5f7fb9a6d2a77afaaa6f0365b'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20420101-20421231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20420101-20421231.nc' 'SHA256' 'b306a2089f1371ab04a470cfdda9c069bd0b536f05da87ac5dbabc3af3de2c73'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20430101-20431231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20430101-20431231.nc' 'SHA256' 'fba41240f4273020556a40c2540d417b3230645895f0efa259e9558883586493'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20440101-20441231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20440101-20441231.nc' 'SHA256' '319393e8032f50a0cd922339467d7dd32bcd8cff1f00abb73f0b94a58ee839c2'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20450101-20451231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20450101-20451231.nc' 'SHA256' '28d91c327327edb94619865e52a2f0ac864bbe8235f16639cf4554c3ea8eada0'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20460101-20461231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20460101-20461231.nc' 'SHA256' '3b845f641f3ccd83f972650959c869da50223e075924896c1fb8f403ba13fcd8'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20470101-20471231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20470101-20471231.nc' 'SHA256' 'b6f049586df49424c566cbcb6d4a4ceab2989ce5f35ae73381021759cf5838f2'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20480101-20481231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20480101-20481231.nc' 'SHA256' 'cae8c2e84e3ac4e631d7e43f75632365002381eabb40ad0ee29dbb83b140df1d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20490101-20491231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20490101-20491231.nc' 'SHA256' 'b2edf8655b7637e887ad994a080f20642700f633973ccabfda561b14cb65a354'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20500101-20501231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20500101-20501231.nc' 'SHA256' '22893186cd6c9c7ce6618e6b20529b92d9807a709bce5ca59650699812c83870'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20510101-20511231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20510101-20511231.nc' 'SHA256' '35680b7e87b24105b7e21197ac1121862f643a89f11cddabcf1d5e2ed63f703d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20520101-20521231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20520101-20521231.nc' 'SHA256' '5511d1ee2df798ad2521c88e88e67ea8e4cb3f65a959844b0a4973a73f5c1649'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20530101-20531231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20530101-20531231.nc' 'SHA256' 'f92e24dba2ca2ed2104428ba4df51f404a02eba269205d9ceed08841e42cb7b7'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20540101-20541231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20540101-20541231.nc' 'SHA256' '04ff3a7473ea5a4d918c9cb1095588f3cb3d51a61e9c23415a14bb155f6a97f1'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20550101-20551231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20550101-20551231.nc' 'SHA256' 'db04608e02368a8667f07ef953859ed65eb24ba58fb30909b1f9aff03410552d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20560101-20561231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20560101-20561231.nc' 'SHA256' '129732b7c55b97acecf2f2fe313ec739330d92dab725b85ff1c130ac87617ac3'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20570101-20571231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20570101-20571231.nc' 'SHA256' '961e79590ccae3d4425b541026ed7b445f0107d0e0c0ea1a86242ca0778f69f8'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20580101-20581231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20580101-20581231.nc' 'SHA256' 'a76ff8baa078a837a59451a1a7ccae9b447eda9f0c7f1f2fc11c56dfb493b054'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20590101-20591231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20590101-20591231.nc' 'SHA256' '455548e214172d61a935a766c4541d47b49baf8e4e9b48a01de3f58993e1a502'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20600101-20601231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20600101-20601231.nc' 'SHA256' 'de0071363e6653732d53173ab135a8eed43541c85d24373204be874a6ced679d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20610101-20611231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20610101-20611231.nc' 'SHA256' '4b6f596d2fda904e94d2f7aacf0a21269d4055f2ada7a255f073478a0f97fe0a'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20620101-20621231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20620101-20621231.nc' 'SHA256' 'ddefe46d8c1221ad8e18736766d91805c3cf86b044a72066ac3f1f6717f691b9'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20630101-20631231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20630101-20631231.nc' 'SHA256' 'a554b90912e3b413324c3c70ffbb37f8d47631ce0ede3d1bcccdadbfb792201b'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20640101-20641231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20640101-20641231.nc' 'SHA256' '674aa4b695ff69e93bab16aa2a033fae3b7771d7c16dbcaba8acde6865071bad'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20650101-20651231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20650101-20651231.nc' 'SHA256' 'e24e90913d83367eec17860fbed596496c72a243c4e962083c5847408f209e84'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20660101-20661231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20660101-20661231.nc' 'SHA256' '6b8bc7de64e373ac8562c885422ec109efaa6af424c1969d2bfd3f08e9a6cdb6'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20670101-20671231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20670101-20671231.nc' 'SHA256' '90fad11cfd669a3e70eb59ff101eed82e1a10e960e464d01def31aaaab0a410a'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20680101-20681231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20680101-20681231.nc' 'SHA256' 'a97a83fb6c375efed29f0cf4bc306e4c55005c0a2baf28148debc0d175e481b2'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20690101-20691231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20690101-20691231.nc' 'SHA256' '2e498ab4a56c248f9b31e734d81226b9b580f058d2a0df862c78dd4abbfe0288'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20700101-20701231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20700101-20701231.nc' 'SHA256' '4c29844b21345d2590da8504f0e3cee1cac8093a7c96fadf131647484a0286a7'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20710101-20711231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20710101-20711231.nc' 'SHA256' '36ca61458da2f315e2061e651e86e5c6379b0cbfdc7de7a0fbe93c6c7eae6e27'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20720101-20721231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20720101-20721231.nc' 'SHA256' 'b36c044d9da5de45f16ec29acf8a79cd8e278e11c739ad47921e2d9e44f07a83'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20730101-20731231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20730101-20731231.nc' 'SHA256' 'f42d449152373e6a4b80cb1f12df8aad5c8a3b6d860c67ecc63f340651210ade'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20740101-20741231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20740101-20741231.nc' 'SHA256' '78e9b9ae6467ee90ee2da3e5218533ec9d425af1303c31667bbeccfb11765d49'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20750101-20751231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20750101-20751231.nc' 'SHA256' '4c556a655d994fc96a65dd6b22254005de0dfbc3542b01609302f6dbc10c05f6'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20760101-20761231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20760101-20761231.nc' 'SHA256' '52d27bbdf0b5cc583b9d63e02140d71faf5858b0fb9e38bdf50d4ec4ff761a61'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20770101-20771231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20770101-20771231.nc' 'SHA256' '5544edc836f4a747788fb1b88f1f1264c1fe52ea78714de112f514b22225e85b'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20780101-20781231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20780101-20781231.nc' 'SHA256' '6f4435719303f75f7ca92d17c1df8de5c1ae104aae9191be8360a843e6915595'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20790101-20791231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20790101-20791231.nc' 'SHA256' 'd135d30acfdda13ba025254ee4e791d7b037f2b0c3c1a58bdaab8b5f2f87093d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20800101-20801231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20800101-20801231.nc' 'SHA256' '7484af3066e945a0ecf140d8ce9a8c090b88de57f634464991fceb01af8823ea'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20810101-20811231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20810101-20811231.nc' 'SHA256' 'f867a6f0d4a5bf34d1c331727d0aa9ccad933412e0b1a3bdf5101bc162839e83'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20820101-20821231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20820101-20821231.nc' 'SHA256' '2abda7cf3c9d358883afe21cc664d8ccd3595484e77c135408ebe25758167da0'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20830101-20831231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20830101-20831231.nc' 'SHA256' '03d5dcbd224ecb84213ec53407f92f30cbc2d8e8a97085837990db4e7dec2f73'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20840101-20841231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20840101-20841231.nc' 'SHA256' '753eb6801f1db5f32a12118b3a4ade5cd79b817dab78e0a1e96e4281166a9fd6'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20850101-20851231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20850101-20851231.nc' 'SHA256' 'a875b02c213664daeea293f20b754cd42f00250ba2a5ca30227e722206a2846d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20860101-20861231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20860101-20861231.nc' 'SHA256' '729c020249af8f35a6615e82948c80aa57f770605ce3505e29621a400a56aa80'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20870101-20871231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20870101-20871231.nc' 'SHA256' '3c9e93adf7a2b82400cb2ee5b3f7c1bd6a00080e59a93f84516912a833ff64fc'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20880101-20881231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20880101-20881231.nc' 'SHA256' '19b1e64574226c82eda928308641bd28e95ad3b200e33e09e6309e2cf2d6404d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20890101-20891231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20890101-20891231.nc' 'SHA256' 'a82cf2986222ebf94da5707c0252375134a8dc0211257950ebd2b30569d1b2e2'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20900101-20901231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20900101-20901231.nc' 'SHA256' 'c597dd53fa9e7d53a6708168d4daa7c112a1c683ce09e93973ac205bb2ebac74'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20910101-20911231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20910101-20911231.nc' 'SHA256' '4071894993b362e9eb3e6676d8fe7419b7d05e1ffc868025382659d038adf2b2'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20920101-20921231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20920101-20921231.nc' 'SHA256' '18985aac05baa2a212632e8ac8781200d8a895c496cbe65414a984fdcd1f9336'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20930101-20931231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20930101-20931231.nc' 'SHA256' 'c313233632a60ffaa594c63b239c372ec1a1a415d9f24e88bac6860727a4a081'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20940101-20941231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20940101-20941231.nc' 'SHA256' '975db65f7e1b92091350a199cda10a4e67f760ad1b2624535fcc1a6e9ad2b9ec'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20950101-20951231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20950101-20951231.nc' 'SHA256' '4cda9eac771708cdc6fc35b943808f6ca25c9e382e4549348e8bd14d385c7e5a'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20960101-20961231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20960101-20961231.nc' 'SHA256' '7bf71e8a671005bf1e9c65365f13737d11816bd99a5a0cf57463deb339d7231d'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20970101-20971231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20970101-20971231.nc' 'SHA256' '53097f8fe75980eca3f72f380aa5730b76963abc147e6c8f120d8dc0a83fd68c'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20980101-20981231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20980101-20981231.nc' 'SHA256' '3813baa38d95f3f09e4776a4cea086a576dfa7b38cfd8ac2d731cc83d70303e8'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20990101-20991231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_20990101-20991231.nc' 'SHA256' 'c3d665e9ab5f4d6c3e1b939dcf4caac439872e5f1cafff48d30b5e711d215e93'
'tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_21000101-21001231.nc' 'https://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/ScenarioMIP/CAS/FGOALS-g3/ssp126/r1i1p1f1/day/tas/gn/v20200928/tas_day_FGOALS-g3_ssp126_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '490eed77b27d2e5c779f33734ab8ee0b5fdf8e269e181b4f3b3cd4e29cbc729a'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 86 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
