#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2025/03/04 01:39:00
# Search URL: http://localhost:8080/esg-search/wget?dataset_id=CMIP6.CMIP.MIROC.MIROC-ES2L.historical.r25i1p1f2.day.hurs.gn.v20210317|esgf.nci.org.au
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?dataset_id=CMIP6.CMIP.MIROC.MIROC-ES2L.historical.r25i1p1f2.day.hurs.gn.v20210317|esgf.nci.org.au'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19500101-19501231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19500101-19501231.nc' 'SHA256' '340e0995a33860161f4e9f5abefec1106a5722706110901f158dbe117a5fe5cc'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19510101-19511231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19510101-19511231.nc' 'SHA256' 'b6bb8595a8f4ea26c0fc30c142353aea9be7e8aae306a68d9658e521297e3f58'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19520101-19521231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19520101-19521231.nc' 'SHA256' '3cf82cb2e4b304c840294b5da18bd0d21e43459f28911a8d9e4fd7bf8c412b3b'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19530101-19531231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19530101-19531231.nc' 'SHA256' '38f5cfe2c8da734236a45ab59c8a785553b81106e5342a044626d2d34ecfea71'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19540101-19541231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19540101-19541231.nc' 'SHA256' '3d2604f499529708bdecda6cd9aeac830da3cf01203e71a739f58ebc3044c315'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19550101-19551231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19550101-19551231.nc' 'SHA256' '78579d07ce5075210a96505317f215112f11cfb8fa37d9fd10610be5a88e366c'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19560101-19561231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19560101-19561231.nc' 'SHA256' 'c33a8b6176ed1ab00e6785f4370d434b80f66f157017c3a7bce67ddf16744d82'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19570101-19571231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19570101-19571231.nc' 'SHA256' '53394b92acc93525cbca3b17782ab6fc8309c444f0dbaa6fdad8c3ca34d369da'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19580101-19581231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19580101-19581231.nc' 'SHA256' '6976ffa1fcf2216e2a7e728ec3ab02d9d0d457ac9f39836d1fef68fd512e6e5e'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19590101-19591231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19590101-19591231.nc' 'SHA256' 'd703aa481c4761e5656b4a688a791adada35e483df890a0bd98b71681c16cea8'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19600101-19601231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19600101-19601231.nc' 'SHA256' 'ca2a82da4569ca1b7ebcfd48d656415c7062c6d42623079c0d405c0236417864'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19610101-19611231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19610101-19611231.nc' 'SHA256' 'b1915aa8df34211272fda045df6c84286a16b306a7ec2df1b8eb403dc0d46ed1'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19620101-19621231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19620101-19621231.nc' 'SHA256' '575e24de565472b0f12af5f0e9ee6bfe17676052fd1b28aed374894506fae24b'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19630101-19631231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19630101-19631231.nc' 'SHA256' '93413255595a4164770f93a62c498993651386afe26a9b555c6bdaf3d48b3a95'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19640101-19641231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19640101-19641231.nc' 'SHA256' '429b1237322fe5355fac2fc5723593affde2c6d415c4af952ffe1e4c4b0baabc'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19650101-19651231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19650101-19651231.nc' 'SHA256' '4b032b8e5ea95c7250190539b53388d2c61bbfb5f97df0df19a2eeec6d7c6539'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19660101-19661231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19660101-19661231.nc' 'SHA256' 'eaa320a134cac1118963a69e036e4685d1369d15a07060def094065ee9aa3235'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19670101-19671231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19670101-19671231.nc' 'SHA256' 'e3102dd36225fcc7ee05992391aebcda8169c2ea49eca5d823f52fb6418607fe'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19680101-19681231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19680101-19681231.nc' 'SHA256' 'dfa9824cafcada7b3912d85d7dac4b1b1f3c3b0f54c21e9af89794446772a170'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19690101-19691231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19690101-19691231.nc' 'SHA256' 'df8249c4a5691f408b9c670da5c11ebca307b2250d830d87fb7d6605689caec7'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19700101-19701231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19700101-19701231.nc' 'SHA256' '8839b67d6638c44902b9e91876b2b3cc58ee1674595f4fb794fe768cc80135e4'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19710101-19711231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19710101-19711231.nc' 'SHA256' 'c306ca8760881f67c47321f00cfb566a7b81eb0fc9d22b686ba706a965db685f'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19720101-19721231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19720101-19721231.nc' 'SHA256' 'd6f5480d30a24a1f730dc8aa650967b70d52fe6af748e1365864a3c707ac8164'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19730101-19731231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19730101-19731231.nc' 'SHA256' '3583b46e759586a5105575358fafd2a5306c67086d57892eb0aa69d25721962f'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19740101-19741231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19740101-19741231.nc' 'SHA256' 'cb8f361bac9655e5d38908a59de601a3bfa73aac2d691dd36ca081a9cf29a281'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19750101-19751231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19750101-19751231.nc' 'SHA256' 'a3adea7f4c95f88f1ed041595b0798c5dcd17c3753c27dee76e980d7cf4b452a'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19760101-19761231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19760101-19761231.nc' 'SHA256' '745e0479486b6cba1b39b8c6aa9906f914956a55f473f932d498b778357a8ca4'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19770101-19771231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19770101-19771231.nc' 'SHA256' 'b1d7e7ad9262a5e12b9d38ecaed20941150ba57d5b9eab9847d8800dae972e56'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19780101-19781231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19780101-19781231.nc' 'SHA256' 'a423daaeb143928ba71f5f862c597aaacb65a19c3cc123314e0a1d6164ba45d4'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19790101-19791231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19790101-19791231.nc' 'SHA256' 'eeaae149e55dcf381beba220a5746d2d339ddc80f638d19f98bade7bd8c5f871'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19800101-19801231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19800101-19801231.nc' 'SHA256' '1298d652f4ca798f2b0cadd050d7d669a31479b00a967f74c1061ea6cb9e46d8'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19810101-19811231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19810101-19811231.nc' 'SHA256' '1ffe19524d693d2b6875b31149fa2d0ca8dbbfaf8c3d7277e8784957f570ff79'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19820101-19821231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19820101-19821231.nc' 'SHA256' '8f8df9553fe11f63a446f5750c5ef77feb985194e6db8f2e0e809a77e5515980'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19830101-19831231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19830101-19831231.nc' 'SHA256' '36f25dade8d40132278f79998da2c6d69a505ffe0cac8f5f7851c1bd3d497cd4'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19840101-19841231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19840101-19841231.nc' 'SHA256' '178aca2c9ccf3b2c3473c2a92dab0351ce09bd0410f3ed62a7c3239ceb157c21'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19850101-19851231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19850101-19851231.nc' 'SHA256' 'fe45df50ab813b4e0c33c4e353a857d4e2a23259021252da177b5d7550bd4b06'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19860101-19861231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19860101-19861231.nc' 'SHA256' '511128df3bab6295d7818ea2121ee2d6dcc405d7ddc602b8eba2d60254179cb3'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19870101-19871231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19870101-19871231.nc' 'SHA256' 'a6c76e186a3abfa2f5caffa0c35128b2fc2fefc96b7940560d678f4cd53469f0'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19880101-19881231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19880101-19881231.nc' 'SHA256' 'f44f3b0c397fc57cb159a252bb843e09cdbcd27bbf384ff5e61f1a503fa87ca5'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19890101-19891231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19890101-19891231.nc' 'SHA256' 'c5caee0343824bec49209b38e0a30fb5b323161a8a496f22a1888b5ff07c638d'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19900101-19901231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19900101-19901231.nc' 'SHA256' 'd8ad7bec2ce036f1513010c2ba37fcfde7898ea0eb9a3ee5d0206fc0c5db755a'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19910101-19911231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19910101-19911231.nc' 'SHA256' 'c192e07532ced0f55463af7dbb641de3fde62cb40de5ad32e75721a61382819e'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19920101-19921231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19920101-19921231.nc' 'SHA256' '5203b520cabff1b73e92f27a419df3761562fa728d26c25f7d30b8653f90cd1a'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19930101-19931231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19930101-19931231.nc' 'SHA256' 'f7a5e9306257b8b508436209747e0769ddb7d7e2762f1fe904498be40f116178'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19940101-19941231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19940101-19941231.nc' 'SHA256' '3e35e6a0480acac9347bd64adf7e9ad030d077e08635e5f76bb7275e5fb53486'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19950101-19951231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19950101-19951231.nc' 'SHA256' 'b518c363e3a601bb3e43356ab4c4558a08b4174b3fd8dca283d4d2936133575a'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19960101-19961231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19960101-19961231.nc' 'SHA256' '7ebb8a8ba8bcb9123e56eabd30f30faf45ffb04cc9bb4492a1f3118b96757421'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19970101-19971231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19970101-19971231.nc' 'SHA256' '3d68a1be08b9b1974cc20315c43752776d33ba1acac280368fa55437c850f06d'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19980101-19981231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19980101-19981231.nc' 'SHA256' 'd2fbb8c0a105e8d385eb857a5aa308662df093d19d3691f6094f65b99be0d0dd'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19990101-19991231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_19990101-19991231.nc' 'SHA256' 'fd8770a5a43d691f878d860692926170805bd7e3278639616b7366d55b8a86d4'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20000101-20001231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20000101-20001231.nc' 'SHA256' 'bd36637cca76a61af24a46f5508c3b14ef7089dfb8f0e3013907e42125156677'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20010101-20011231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20010101-20011231.nc' 'SHA256' '0c8ded6b75b8189e7e85f502f75f8f5f36864d35c982ea1fb92393a9af1bf0b8'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20020101-20021231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20020101-20021231.nc' 'SHA256' '4bada392a6bc27da3020225318d2d6f894a9eb8bc61917b2d850098ff7df7bc5'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20030101-20031231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20030101-20031231.nc' 'SHA256' '0d92f691d99a7c68877f1f49e22bc3202b3122d5385c1e2353a36160789dcc01'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20040101-20041231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20040101-20041231.nc' 'SHA256' '06407edc7169258b33a2f44e6414ee14d7c91349e8e8c3beb8fec48aa18c0a5c'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20050101-20051231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20050101-20051231.nc' 'SHA256' '44b6fb43648217c2d7799605334b7977434e08578f0d3cc74224a37861153f54'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20060101-20061231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20060101-20061231.nc' 'SHA256' '14f320cd80f60b8e2f71ec48fd520ae3a791b89baa2f0f35dd8dde960a3630c5'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20070101-20071231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20070101-20071231.nc' 'SHA256' 'f27044e8a1b84f29079590a266322723009ee29f723da30fb947e349834e9613'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20080101-20081231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20080101-20081231.nc' 'SHA256' '30bc0957e34f47eba148e86321b0bbcaeef19fa5792741fca9bdb771b6d91e4a'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20090101-20091231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20090101-20091231.nc' 'SHA256' 'df835561575dd1b67f4326be81a27369850619d67729df2b106962cb8d24a7f7'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20100101-20101231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20100101-20101231.nc' 'SHA256' '97ee604841b7720cba64dfc6122a010bae3f424ffdd1f38a3af2756c3b929685'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20110101-20111231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20110101-20111231.nc' 'SHA256' '36c46956f9521aaf1daaca65399a128a5d7f3f01662a250e30d4a085f572be0e'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20120101-20121231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20120101-20121231.nc' 'SHA256' 'd5567f09b18493c44d093d9e8f3792f6fad39176ed1de43d4c84625ecfb36781'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20130101-20131231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20130101-20131231.nc' 'SHA256' '63cd8408e07ce55a09f4de83e368c1821a284333c4f5b579270b2986891cbe9d'
'hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20140101-20141231.nc' 'https://esgf.nci.org.au/thredds/fileServer/esgcet/replica/CMIP6/CMIP/MIROC/MIROC-ES2L/historical/r25i1p1f2/day/hurs/gn/v20210317/hurs_day_MIROC-ES2L_historical_r25i1p1f2_gn_20140101-20141231.nc' 'SHA256' '46b851cc7786f9c6bb1d99c92e155ca10543825a390d3780c3b1d83fc42b7816'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 165 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
