#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by localhost - 2025/01/04 04:16:40
# Search URL: http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.tas.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.tasmax.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.tasmin.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.hur.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.pr.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.rsds.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.sfcWind.gn.v20190710|esgf-data04.diasjp.net
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://localhost:8080/esg-search/wget?dataset_id=CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.tas.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.tasmax.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.tasmin.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.hur.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.pr.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.rsds.gn.v20190710|esgf-data04.diasjp.net,CMIP6.ScenarioMIP.DKRZ.MPI-ESM1-2-HR.ssp370.r1i1p1f1.day.sfcWind.gn.v20190710|esgf-data04.diasjp.net'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' 'b2eb378fb2cf303f4b8747689bc5fde72731cbd107ea7efdda163664bd08fb43'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' '98e336840cdb849e620465d88b6683ef8c6f35a5ed185e10983ec08d329062c3'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' '25af3ce33302dfd9d852f819b48a204045f21ae302ee8d4d1be784ecd00a4b9e'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' 'fc9ebf2bc463dfcb29a1bf5930361564ecff29249ea6806b7dcb90ff0dcb0b27'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' '1a3fa78acbe3d1d90f04a88f7ff5e21bec93190ae0d219618581a96636de85e3'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' 'd6f23a8f34369ec6bbcba1d087b468ef603c7f988a142800e620e61839ed49a0'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' '86c0cde75bbae491ad716b13ab6024f846e5ebfb630dda32b98697922e29abf8'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' 'e58660e499fdae57e17ad0207ada0267134ece41a16fc29b433ee675c8d7a9d1'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' 'd484e5de2a2beecdaf1c4c2232397f036f361e3ec9a128f87e57b8919e55dd36'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' '367191389a14ee6e8735033e5a1a142185ffe4721ce73dc4c3955c6eef3b00f9'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' 'c5937c2ee595ebdb9a49f5ca9cf1814f42a2bb04646ff5582292255d8ac0f495'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' '9a70973057262e32aec63e4da2ab2b35fdec58efa09033d9e89e2991121ece4d'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' 'd0bb60a486e91d99d78b1906e3f6447c2b95fb01499c464713d35789b4b4ca98'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' 'f438390e13447ea7a1ae9dcf4366e2d8ad813cc04322e4e0bbedb2e2cd4d68b7'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' '3a79b9778645d5fd10fe809753ade8f2e93716a0c196c7d17df8857ac405dec4'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' 'e0b1ac6a299fc1d3843de496f94b50302358abc55541909703e0f97c7eb9cd20'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' 'd847025517783a6dfd2858746cc5b9bef3bbc926786d71ea91575b1c5990606f'
'hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/hur/gn/v20190710/hur_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '3e469da425e245752b75fbc2dedb05f92191d2370f281d0179ecb34d731d680b'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' 'b53fa1994de69e62de44b1e8360da6419a84919ef4a48f379ac3ea766f508118'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' 'c27ee7d4b797b5b405e4448c9a34bb783faabcebb7fe0445e10a7340f9dd922a'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' '78846a7d0c86c20d8de82fbbb86077be6f4618af2e26e50aac73004cb398a43a'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' '1ef5723eb1417b2a786dd1d01ae587954e101a140940b0294586b9c52ff83377'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' 'ca60cdcad1e45ca513f9c50d4e33800e30b163331abe3e78a4d912e1087e04db'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' 'a237cd7728dff4005eea33bd870f8db543c0f709449b0a71fbbfbf1dfbd162a5'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' '0bc119ef11cb29d800ba9d70116c8dfc55b5723fca29b601ad2a06170a18467a'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' '96d5e525832fe88265c633e3854a210303da9ac2b04d9e0810ec28de4a08eb01'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' '0aa3ba52d45a80226bee2b5c5f37bc8ca2f1b91c7e51cd1a742bd64612031d8d'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' 'b2962785973a1c538514fe345a9508685d775ef0426def8207f75798ac837400'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' '3f2fc8d93a623f3af29ca79571a0e62fde20aaf6340ecdecb8721228bbcd656f'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' '8bf17077e8b43841351a0eaf1452bbfd705dc2a7b73a2af96ca8ddb390c9ab5a'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' 'a376542bf2f2a883e2e4df91fb8af2217a4003669683252bcb2adabd5d014161'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' '73a554aeaad65529eb13fb9bc261bb67f43d5f3437e3b15196c9e32a3eca4904'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' 'f87ff424a8fa535ea1babd808f5556786f8134093529f9484484f19659d4be36'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' '48e20b18cf61067efdf6720f813384f4d0136cc2550a7ece9be983e458ec20f1'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' 'f63e0224ed9828e48b174655a8d2825dbdbeaae771564e6ed58b47a17b71f0e9'
'pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/pr/gn/v20190710/pr_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '053b23798ed71be74a02a02b872fac8df4f1a80e4930aae8a67c9f8c719c29ef'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' '2a9f46f465f1e1852750190d910d4c94d36bfee4a14ee79b51b2d5919596e8e9'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' '19432332d7e0091307d75ab4d88a19353bc8d69c69026347ad5f10c1ffe9bc4c'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' '883b5e3f1dc9d765ef00ba9004793068ef0a3081235cce3d2eeb27c47c6f50f4'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' 'f3e254af5ac8fdac12e12970e9761c321475d66a33d98ea67f94317aaeace36e'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' 'ee0fbc29afbe1e0ad7a77d7be9ebf4ca0db1c1c7c503ca3d899da2ca3580f0a1'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' '5ef4f6efad9c6039c4c219cd326e342836d7b82de966fb9298e27b0fe6e7283d'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' 'b00a7795d9d9bdd5719a17c195dd14035ea17e75522fe9a7f627fb87cd0bfc65'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' '4e0705d390770422d54fbe83a4a448418c62c32ed53dc9e1a651798c686303a4'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' 'f9de526c21836d2132a2669e6682ec4cbf19e86e521722e38f14d5bdddc4fd41'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' '2f27c0c92ef05bfcc6012773292cd69d2ee2681c3736481c17eff38e5188d6da'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' 'e4fd053f74cc016bd63d56306c558e3cdf3156936cfcca64af8d2e57f4fca597'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' '55cb9ae56c37fe3df0795bbaa9b45fd7a9dd1dc85298bce9727ec1ca61303a5b'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' 'a3ff12f504b2cd49e6a5813cad97e7c9777c006b0fc98dd2de5e8c5d6bf852b1'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' '1ec70bc30a09082ac4102a36a5dddb6f8ae3e3083f2dc17bb4a356703b179a92'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' 'a292960a86b0325622b330309cbd1196f121cc8bd239fecbd486b543e14b749e'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' 'c72d7d76c6bfec4162d471d55787aff1a53fd14e23f305e02d54c43e869a172d'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' 'c1dd4b911428d8ad3e2e8e9e9d804d345d4766470d3c6b257a0973b7c9fe8006'
'rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/rsds/gn/v20190710/rsds_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '891bad7602366a9f098c79136a32117adb222d25ff7fca5b08ba12d7cbb9b285'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' '663b50983ba805b98afb0da2e38315f7d2d3f81bf8152683318fe5d4bd24e8f5'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' '10fd020367ac5b3bb4a9fcb1c8c3040b0b49c2ec8fd892135b87567612abbd79'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' 'af51cf11ab853cc9d78b04d3336ccb3cc55fd3b01e0a53f1b126939b24207022'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' 'e42efbb744f8dddfb5b827136fdd051b6cb633430ac7c8f686243cc1e49346e9'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' '05a989b42df27643c6effd859dfaedb32aa7381eac748e076f40b85cc57d7af4'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' 'dd3bd4574356937d4ac216c3a983d2c7e9ecbd6a173f63274f892a4d5a5532fc'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' 'e13b31ad709ac60d41a1f7cf5c53c1847a66a4141365d73e8f9f25d381a7152c'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' '4b0b52c2aa176adef1e72ca6b53e7d9fdd759f393e05e910dc42177fc6e27ba7'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' '29683863dfc62d7cede78963d4ffaed7f8bb9b2b9184bc1b9866813a3535bf13'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' '41ee7aaddde7878a39694ee59eaf8c14f9907dc8228047b2666d0002e0dd2c14'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' '38c96cffa44228ad9509a8fb7d109212b3d8aca8b449d770f7baa9b631e78d7b'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' '454959a4828fbb71956c293f6df52092d277a23d869fffc5f074c8e7e96f8117'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' 'd9abf3abfbd372ad769eef9abcc09ce78bf0b0dee16f139f28ac50674041efb9'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' 'f63b0e290b2f784fe6c074e2e14f14370af417c0c419cebbf0c213567016153e'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' '3fd532c46cd198e00cb1253758c70ba22cf3297c13309dc98008dce40799d572'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' '10b174277759c1acdcfbac0bae1ee2e19680e2f5283197a2e3dfb8bb8efde829'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' '5c4efa0b8ff9d35c69f85dedf0a57abf1fef7830e4fe59510da707b90c6d8733'
'sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/sfcWind/gn/v20190710/sfcWind_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' 'f2eb8f608078c58e336fd89440e40d6d6ba694af44f75b2de709dbd99c087db5'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' '1c30d792caef46847b205a1f0fc51d52a3a58d447ed0da7f4b18b01e0b9ff219'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' '09af45502bf20a6763870f0cfce61c503a96e4e2cd6e772ad98a6da714759fc8'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' 'f7a23520708db50142c574b87b2b3a1db4baaa91c67c0ea025a12f3df8d2ba7c'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' '0e419390763688d76b683df34a2d94b34259bfa6073a7a28558b67dd5b3573f7'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' '1e5cb038bb471e22eb4e93e53d800ab371cc52e5e0bcfb5a633c9de9157942f8'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' 'f7c459420e313d4d187b74c091bf7b9835f59d70756925c9b611c542478ea318'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' 'be403ffe82cc7046e67b1be6ca6d6fdccff065385291cdff82c6dd89ca16fcb4'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' 'ff1f57f64bacc9e4129c2b67b79e30005e8a67d731d8d0e5cc16d84e6248feea'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' '72fc19af53a42c8028556e01f74124e643d1fcfc0b4eca034b9100e3261b4d5f'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' '925a44a7905efdc536ac471e529e743a3f63565e44e2aefc1f18da79d6a0eee4'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' '48ab44da4ed20b91314c2cdfde06d7fbf52bd2cb4d91af86d1937be129e80d8b'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' '86b41357d91bbc3a9b99672491dd1f12d7b1b98111a8bdbcfc60357a59d5013f'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' '7dc742fb367ffc04ccd9dd48152b9a5163098c0d627212552f3d8f244190f169'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' '213bc3d686cf7d92a63c58e043d131517428e248eeab4be2dabef065c4aee93a'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' '07c5d9aa1a387456af687d0fda5c8cdca1c79e50e39ba92a4f7c851437ea4365'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' 'c70ecb09c16032427e27171a4e67a287ddbd3185ee3adf8bee545783a848bf43'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' '71be23c0b4cecc0150fe5a75bdd2487c18d538229d49edc35d1f343e2a2e5fc1'
'tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tas/gn/v20190710/tas_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '56685a1dd5183da5671e0adba7a1327d1712e0e7f3c1dd2b67ce118b3e86386e'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' '92b1934f2ff44ec9408049b91cb465e711be5ff282861888295316824454852d'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' 'b44f034b6ffa920a36ce7c550ea5e9755028cebfbdfc40b04ab8fec6991d1e02'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' '2280793df956729a0c2af528fb349ed10f1efbad6ba8d0b97ee9731be9e48b76'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' 'c8ad91ebbad76aa85ff8cc3301f5deada32a3355436b5f9e118358c9827384e0'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' '3fa52c21a040dd7368e2f3a217bf3a883302f86dab77e18e3d61cef30d0bc315'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' 'b251d2717680064f8e24c29f8d5cd1c73cc9d74e53447c26dd3d41382fe6f0e6'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' '0a640db62bf82d7c1d13cd4f401dc3875d35c6a6ffdcc2afbe36bd506f2ccd61'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' '9902fe0b7db0eb5bf74b8dc1266c95517fc5fae700bc10047012913a7a6bb7a0'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' 'a0addf5e5628041f642b133b49dd22865f9039ce63cfdcd8deda45c96daa091d'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' 'a9d3641dfacbdc15dabee262399fdf8301b2260c51da2f13f2f0222017809d24'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' '7808745b644999e314e9b545515b552ed223cfa6f32d2e01bd7cf5eace866b99'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' 'e8aad2d8cf6f6c2e421996c4d66e64f563949d180597109bc41ebc7c2cb727c2'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' '1cfde9ed100982ed1f3af3c640c9d9063246feb96ea8e464e7d11224b0895e3f'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' 'aac38c5bf11838dad97e0bb562fb335a91c9fad1f98e3cdef22e75bfc1cafc04'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' '426290c639bcd1736c8979f3ae2c82650df29184c7199c9e106b47e4f36221cb'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' '1684bbab23eeb537e878e04e09b6b14a8aed51ca3d419edd73e5df647f35156d'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' 'e2608cf6709aca151613b7c32df30b666cf585d1dc7e8e0207f25296ec76abe1'
'tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmax/gn/v20190710/tasmax_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '06b94b7a21352d73a4e7e74d84c3fe9daaed94bb76525b841834fa5caf6adeca'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20150101-20191231.nc' 'SHA256' 'df9e8fcf2de6f905285a0a11312e98f6171dfb1632dcddf15976cadb2e4e6a0a'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20200101-20241231.nc' 'SHA256' '37a0137604fb16b21f69fe5bf18c4e48f607b3750bf5dbbb5afeb5d3f38c3b1a'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20250101-20291231.nc' 'SHA256' '8a8861bf5304520e56d1a340901995c860305ca0d5a3a413d9022cb17ad19075'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20300101-20341231.nc' 'SHA256' '6f38d1ddfc9387eadd491d95e3f46e070ca890be8de24f1208bf370c707355ed'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20350101-20391231.nc' 'SHA256' '10858e55d52b2f3f1131b94819be850f6440a0b4d552d9f82f1019afd8d3bc31'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20400101-20441231.nc' 'SHA256' 'af21c3a8b7a89575a93c38e3588d86e59ed81b4cba34a429956129a913c7db3f'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20450101-20491231.nc' 'SHA256' '9c81456db40b49644d2916e78ee4428f9d3278607cdf277d5a268ce52c0f00f3'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20500101-20541231.nc' 'SHA256' '1dee384c30025e8ecc84114feb3edb1f7ba828449b840b750f3d246ee5168275'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20550101-20591231.nc' 'SHA256' 'aa34e788dc31d88f6fd38c0fdebc00f1c2d3331b071cb47f5b31840a0502272f'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20600101-20641231.nc' 'SHA256' 'c8ffeb4f728a122eaab0756e20913090dc2f936c11a0c7e9d29eaf88c2c4565c'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20650101-20691231.nc' 'SHA256' '11575e16fa9c6d41f7106a58155655e5a318899eecbd946794f6d3a0636d85de'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20700101-20741231.nc' 'SHA256' '3c7f4e5b05f83cf79115e5fdf11ff70512258da5a8f71efa705853b285ef70eb'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20750101-20791231.nc' 'SHA256' 'e288bced78e7ca3b2f9aabc69fef08853c13c8af82d410763b58c988ef65b876'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20800101-20841231.nc' 'SHA256' '1d305c9aa42c114a9c9d68a02e4835895894a196ad9e071dd71d16f41b39ffe4'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20850101-20891231.nc' 'SHA256' '538b2e5f8a61ea952bf938c6138e15a32ed2a646334b29ee8de139ff4353aad0'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20900101-20941231.nc' 'SHA256' 'b52d0d3c638899890e1087e5f38446a0a7282692ae42d6052061216021e78606'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_20950101-20991231.nc' 'SHA256' '0d9b1e11046e5e042eda5008d79f93eaa5058eea005f72098c6e9ae0a25b22d9'
'tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'http://esgf-data04.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/ScenarioMIP/DKRZ/MPI-ESM1-2-HR/ssp370/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-HR_ssp370_r1i1p1f1_gn_21000101-21001231.nc' 'SHA256' '3ee64a13ec676e3907135535bfb098b6317ca87784468a70a34de07cf2ca6da6'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 126 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
